export type CityTaxLocation = {
  slug: string;
  name: string;
  stateSlug: string;
  stateName: string;
  localTaxRate?: number;
  note?: string;
  nearby?: string[];
};

export const CITY_LOCATIONS: CityTaxLocation[] = [
  { slug: "new-york-city", name: "New York City", stateSlug: "new-york", stateName: "New York", localTaxRate: 0.03876, note: "New York City also layers in a city income tax on top of New York state tax.", nearby: ["buffalo", "yonkers"] },
  { slug: "los-angeles", name: "Los Angeles", stateSlug: "california", stateName: "California", nearby: ["san-diego", "san-jose"] },
  { slug: "chicago", name: "Chicago", stateSlug: "illinois", stateName: "Illinois", nearby: ["aurora", "rockford"] },
  { slug: "houston", name: "Houston", stateSlug: "texas", stateName: "Texas", nearby: ["dallas", "austin"] },
  { slug: "phoenix", name: "Phoenix", stateSlug: "arizona", stateName: "Arizona", nearby: ["tucson", "mesa"] },
  { slug: "philadelphia", name: "Philadelphia", stateSlug: "pennsylvania", stateName: "Pennsylvania", localTaxRate: 0.0375, note: "Philadelphia wage tax can materially lower take-home pay compared with the rest of Pennsylvania.", nearby: ["pittsburgh", "allentown"] },
  { slug: "san-antonio", name: "San Antonio", stateSlug: "texas", stateName: "Texas", nearby: ["austin", "houston"] },
  { slug: "san-diego", name: "San Diego", stateSlug: "california", stateName: "California", nearby: ["los-angeles", "san-jose"] },
  { slug: "dallas", name: "Dallas", stateSlug: "texas", stateName: "Texas", nearby: ["fort-worth", "austin"] },
  { slug: "jacksonville", name: "Jacksonville", stateSlug: "florida", stateName: "Florida", nearby: ["miami", "tampa"] },
  { slug: "austin", name: "Austin", stateSlug: "texas", stateName: "Texas", nearby: ["san-antonio", "dallas"] },
  { slug: "fort-worth", name: "Fort Worth", stateSlug: "texas", stateName: "Texas", nearby: ["dallas", "arlington"] },
  { slug: "san-jose", name: "San Jose", stateSlug: "california", stateName: "California", nearby: ["san-francisco", "oakland"] },
  { slug: "columbus", name: "Columbus", stateSlug: "ohio", stateName: "Ohio", note: "Ohio local income taxes can vary by municipality, so take-home pay may differ slightly across the metro.", nearby: ["cleveland", "cincinnati"] },
  { slug: "charlotte", name: "Charlotte", stateSlug: "north-carolina", stateName: "North Carolina", nearby: ["raleigh", "greensboro"] },
  { slug: "indianapolis", name: "Indianapolis", stateSlug: "indiana", stateName: "Indiana", nearby: ["fort-wayne", "evansville"] },
  { slug: "san-francisco", name: "San Francisco", stateSlug: "california", stateName: "California", nearby: ["oakland", "san-jose"] },
  { slug: "seattle", name: "Seattle", stateSlug: "washington", stateName: "Washington", nearby: ["spokane", "tacoma"] },
  { slug: "denver", name: "Denver", stateSlug: "colorado", stateName: "Colorado", nearby: ["colorado-springs", "aurora"] },
  { slug: "oklahoma-city", name: "Oklahoma City", stateSlug: "oklahoma", stateName: "Oklahoma", nearby: ["tulsa", "norman"] },
  { slug: "nashville", name: "Nashville", stateSlug: "tennessee", stateName: "Tennessee", nearby: ["memphis", "knoxville"] },
  { slug: "el-paso", name: "El Paso", stateSlug: "texas", stateName: "Texas", nearby: ["lubbock", "austin"] },
  { slug: "washington", name: "Washington", stateSlug: "district-of-columbia", stateName: "District of Columbia", nearby: ["baltimore", "arlington"] },
  { slug: "las-vegas", name: "Las Vegas", stateSlug: "nevada", stateName: "Nevada", nearby: ["henderson", "reno"] },
  { slug: "boston", name: "Boston", stateSlug: "massachusetts", stateName: "Massachusetts", nearby: ["worcester", "springfield-ma"] },
  { slug: "portland", name: "Portland", stateSlug: "oregon", stateName: "Oregon", nearby: ["salem", "eugene"] },
  { slug: "louisville", name: "Louisville", stateSlug: "kentucky", stateName: "Kentucky", nearby: ["lexington", "bowling-green"] },
  { slug: "detroit", name: "Detroit", stateSlug: "michigan", stateName: "Michigan", localTaxRate: 0.024, note: "Detroit residents pay a city income tax, so take-home pay can be lower than elsewhere in Michigan.", nearby: ["grand-rapids", "ann-arbor"] },
  { slug: "memphis", name: "Memphis", stateSlug: "tennessee", stateName: "Tennessee", nearby: ["nashville", "knoxville"] },
  { slug: "baltimore", name: "Baltimore", stateSlug: "maryland", stateName: "Maryland", note: "Maryland counties and Baltimore City impose local income taxes in addition to the state rate.", nearby: ["washington", "annapolis"] },
  { slug: "milwaukee", name: "Milwaukee", stateSlug: "wisconsin", stateName: "Wisconsin", nearby: ["madison", "green-bay"] },
  { slug: "albuquerque", name: "Albuquerque", stateSlug: "new-mexico", stateName: "New Mexico", nearby: ["santa-fe", "las-cruces"] },
  { slug: "tucson", name: "Tucson", stateSlug: "arizona", stateName: "Arizona", nearby: ["phoenix", "mesa"] },
  { slug: "fresno", name: "Fresno", stateSlug: "california", stateName: "California", nearby: ["bakersfield", "sacramento"] },
  { slug: "mesa", name: "Mesa", stateSlug: "arizona", stateName: "Arizona", nearby: ["phoenix", "scottsdale"] },
  { slug: "sacramento", name: "Sacramento", stateSlug: "california", stateName: "California", nearby: ["oakland", "fresno"] },
  { slug: "atlanta", name: "Atlanta", stateSlug: "georgia", stateName: "Georgia", nearby: ["augusta", "columbus-ga"] },
  { slug: "kansas-city", name: "Kansas City", stateSlug: "missouri", stateName: "Missouri", nearby: ["st-louis", "springfield-mo"] },
  { slug: "colorado-springs", name: "Colorado Springs", stateSlug: "colorado", stateName: "Colorado", nearby: ["denver", "aurora"] },
  { slug: "miami", name: "Miami", stateSlug: "florida", stateName: "Florida", nearby: ["orlando", "tampa"] },
  { slug: "raleigh", name: "Raleigh", stateSlug: "north-carolina", stateName: "North Carolina", nearby: ["charlotte", "greensboro"] },
  { slug: "omaha", name: "Omaha", stateSlug: "nebraska", stateName: "Nebraska", nearby: ["lincoln", "des-moines"] },
  { slug: "long-beach", name: "Long Beach", stateSlug: "california", stateName: "California", nearby: ["los-angeles", "anaheim"] },
  { slug: "virginia-beach", name: "Virginia Beach", stateSlug: "virginia", stateName: "Virginia", nearby: ["norfolk", "chesapeake"] },
  { slug: "oakland", name: "Oakland", stateSlug: "california", stateName: "California", nearby: ["san-francisco", "san-jose"] },
  { slug: "minneapolis", name: "Minneapolis", stateSlug: "minnesota", stateName: "Minnesota", nearby: ["st-paul", "rochester-mn"] },
  { slug: "tulsa", name: "Tulsa", stateSlug: "oklahoma", stateName: "Oklahoma", nearby: ["oklahoma-city", "norman"] },
  { slug: "bakersfield", name: "Bakersfield", stateSlug: "california", stateName: "California", nearby: ["fresno", "los-angeles"] },
  { slug: "wichita", name: "Wichita", stateSlug: "kansas", stateName: "Kansas", nearby: ["topeka", "kansas-city"] },
  { slug: "arlington", name: "Arlington", stateSlug: "texas", stateName: "Texas", nearby: ["dallas", "fort-worth"] },
  { slug: "aurora", name: "Aurora", stateSlug: "colorado", stateName: "Colorado", nearby: ["denver", "colorado-springs"] },
  { slug: "tampa", name: "Tampa", stateSlug: "florida", stateName: "Florida", nearby: ["orlando", "st-petersburg"] },
  { slug: "new-orleans", name: "New Orleans", stateSlug: "louisiana", stateName: "Louisiana", nearby: ["baton-rouge", "lafayette"] },
  { slug: "cleveland", name: "Cleveland", stateSlug: "ohio", stateName: "Ohio", note: "Ohio municipalities often levy local income taxes, so metro-area take-home pay may vary a bit from the state average.", nearby: ["columbus", "cincinnati"] },
  { slug: "anaheim", name: "Anaheim", stateSlug: "california", stateName: "California", nearby: ["los-angeles", "long-beach"] },
  { slug: "honolulu", name: "Honolulu", stateSlug: "hawaii", stateName: "Hawaii", nearby: ["hilo", "kahului"] },
  { slug: "henderson", name: "Henderson", stateSlug: "nevada", stateName: "Nevada", nearby: ["las-vegas", "reno"] },
  { slug: "stockton", name: "Stockton", stateSlug: "california", stateName: "California", nearby: ["sacramento", "oakland"] },
  { slug: "lexington", name: "Lexington", stateSlug: "kentucky", stateName: "Kentucky", nearby: ["louisville", "bowling-green"] },
  { slug: "corpus-christi", name: "Corpus Christi", stateSlug: "texas", stateName: "Texas", nearby: ["san-antonio", "houston"] },
  { slug: "riverside", name: "Riverside", stateSlug: "california", stateName: "California", nearby: ["los-angeles", "san-bernardino"] },
  { slug: "newark", name: "Newark", stateSlug: "new-jersey", stateName: "New Jersey", nearby: ["jersey-city", "paterson"] },
  { slug: "saint-paul", name: "Saint Paul", stateSlug: "minnesota", stateName: "Minnesota", nearby: ["minneapolis", "rochester-mn"] },
  { slug: "cincinnati", name: "Cincinnati", stateSlug: "ohio", stateName: "Ohio", localTaxRate: 0.018, note: "Cincinnati residents can face a city earnings tax on top of Ohio state income taxes.", nearby: ["columbus", "cleveland"] },
  { slug: "st-louis", name: "St. Louis", stateSlug: "missouri", stateName: "Missouri", nearby: ["kansas-city", "springfield-mo"] },
  { slug: "pittsburgh", name: "Pittsburgh", stateSlug: "pennsylvania", stateName: "Pennsylvania", localTaxRate: 0.03, note: "Pennsylvania local earned-income taxes can vary, so Pittsburgh-area take-home pay may differ slightly by municipality.", nearby: ["philadelphia", "allentown"] },
  { slug: "greensboro", name: "Greensboro", stateSlug: "north-carolina", stateName: "North Carolina", nearby: ["raleigh", "charlotte"] },
  { slug: "lincoln", name: "Lincoln", stateSlug: "nebraska", stateName: "Nebraska", nearby: ["omaha", "des-moines"] },
  { slug: "plano", name: "Plano", stateSlug: "texas", stateName: "Texas", nearby: ["dallas", "arlington"] },
  { slug: "anchorage", name: "Anchorage", stateSlug: "alaska", stateName: "Alaska", nearby: ["fairbanks", "juneau"] },
  { slug: "orlando", name: "Orlando", stateSlug: "florida", stateName: "Florida", nearby: ["tampa", "miami"] },
  { slug: "irvine", name: "Irvine", stateSlug: "california", stateName: "California", nearby: ["anaheim", "los-angeles"] },
  { slug: "jersey-city", name: "Jersey City", stateSlug: "new-jersey", stateName: "New Jersey", nearby: ["newark", "paterson"] },
  { slug: "durham", name: "Durham", stateSlug: "north-carolina", stateName: "North Carolina", nearby: ["raleigh", "greensboro"] },
  { slug: "chula-vista", name: "Chula Vista", stateSlug: "california", stateName: "California", nearby: ["san-diego", "los-angeles"] },
  { slug: "toledo", name: "Toledo", stateSlug: "ohio", stateName: "Ohio", nearby: ["cleveland", "columbus"] },
  { slug: "fort-wayne", name: "Fort Wayne", stateSlug: "indiana", stateName: "Indiana", nearby: ["indianapolis", "south-bend"] },
  { slug: "st-petersburg", name: "St. Petersburg", stateSlug: "florida", stateName: "Florida", nearby: ["tampa", "orlando"] },
  { slug: "laredo", name: "Laredo", stateSlug: "texas", stateName: "Texas", nearby: ["san-antonio", "houston"] },
  { slug: "buffalo", name: "Buffalo", stateSlug: "new-york", stateName: "New York", nearby: ["rochester-ny", "yonkers"] },
  { slug: "madison", name: "Madison", stateSlug: "wisconsin", stateName: "Wisconsin", nearby: ["milwaukee", "green-bay"] },
  { slug: "lubbock", name: "Lubbock", stateSlug: "texas", stateName: "Texas", nearby: ["el-paso", "austin"] },
  { slug: "chandler", name: "Chandler", stateSlug: "arizona", stateName: "Arizona", nearby: ["mesa", "phoenix"] },
  { slug: "scottsdale", name: "Scottsdale", stateSlug: "arizona", stateName: "Arizona", nearby: ["phoenix", "mesa"] },
  { slug: "reno", name: "Reno", stateSlug: "nevada", stateName: "Nevada", nearby: ["las-vegas", "henderson"] },
  { slug: "glendale", name: "Glendale", stateSlug: "arizona", stateName: "Arizona", nearby: ["phoenix", "scottsdale"] },
  { slug: "gilbert", name: "Gilbert", stateSlug: "arizona", stateName: "Arizona", nearby: ["mesa", "chandler"] },
  { slug: "winston-salem", name: "Winston-Salem", stateSlug: "north-carolina", stateName: "North Carolina", nearby: ["greensboro", "charlotte"] },
  { slug: "north-las-vegas", name: "North Las Vegas", stateSlug: "nevada", stateName: "Nevada", nearby: ["las-vegas", "henderson"] },
  { slug: "norfolk", name: "Norfolk", stateSlug: "virginia", stateName: "Virginia", nearby: ["virginia-beach", "chesapeake"] },
  { slug: "chesapeake", name: "Chesapeake", stateSlug: "virginia", stateName: "Virginia", nearby: ["norfolk", "virginia-beach"] },
  { slug: "garland", name: "Garland", stateSlug: "texas", stateName: "Texas", nearby: ["dallas", "plano"] },
  { slug: "irving", name: "Irving", stateSlug: "texas", stateName: "Texas", nearby: ["dallas", "arlington"] },
  { slug: "hialeah", name: "Hialeah", stateSlug: "florida", stateName: "Florida", nearby: ["miami", "orlando"] },
  { slug: "fremont", name: "Fremont", stateSlug: "california", stateName: "California", nearby: ["san-jose", "oakland"] },
  { slug: "boise", name: "Boise", stateSlug: "idaho", stateName: "Idaho", nearby: ["nampa", "meridian"] },
  { slug: "richmond", name: "Richmond", stateSlug: "virginia", stateName: "Virginia", nearby: ["norfolk", "virginia-beach"] },
  { slug: "baton-rouge", name: "Baton Rouge", stateSlug: "louisiana", stateName: "Louisiana", nearby: ["new-orleans", "lafayette"] },
  { slug: "spokane", name: "Spokane", stateSlug: "washington", stateName: "Washington", nearby: ["seattle", "tacoma"] },
  { slug: "des-moines", name: "Des Moines", stateSlug: "iowa", stateName: "Iowa", nearby: ["cedar-rapids", "omaha"] },
  { slug: "tacoma", name: "Tacoma", stateSlug: "washington", stateName: "Washington", nearby: ["seattle", "spokane"] },
  { slug: "san-bernardino", name: "San Bernardino", stateSlug: "california", stateName: "California", nearby: ["riverside", "los-angeles"] },
  { slug: "modesto", name: "Modesto", stateSlug: "california", stateName: "California", nearby: ["stockton", "sacramento"] },
  { slug: "fontana", name: "Fontana", stateSlug: "california", stateName: "California", nearby: ["riverside", "san-bernardino"] },
  { slug: "santa-ana", name: "Santa Ana", stateSlug: "california", stateName: "California", nearby: ["anaheim", "irvine"] },
  { slug: "moreno-valley", name: "Moreno Valley", stateSlug: "california", stateName: "California", nearby: ["riverside", "fontana"] },
  { slug: "fayetteville", name: "Fayetteville", stateSlug: "north-carolina", stateName: "North Carolina", nearby: ["raleigh", "charlotte"] },
  { slug: "birmingham", name: "Birmingham", stateSlug: "alabama", stateName: "Alabama", nearby: ["montgomery", "huntsville"] },
  { slug: "rochester-ny", name: "Rochester", stateSlug: "new-york", stateName: "New York", nearby: ["buffalo", "yonkers"] },
  { slug: "salt-lake-city", name: "Salt Lake City", stateSlug: "utah", stateName: "Utah", nearby: ["provo", "west-valley-city"] },
  { slug: "yonkers", name: "Yonkers", stateSlug: "new-york", stateName: "New York", nearby: ["new-york-city", "buffalo"] },
  { slug: "nampa", name: "Nampa", stateSlug: "idaho", stateName: "Idaho", nearby: ["boise", "meridian"] },
  { slug: "surprise", name: "Surprise", stateSlug: "arizona", stateName: "Arizona", nearby: ["phoenix", "glendale"] },
  { slug: "augusta", name: "Augusta", stateSlug: "georgia", stateName: "Georgia", nearby: ["atlanta", "savannah"] },
  { slug: "provo", name: "Provo", stateSlug: "utah", stateName: "Utah", nearby: ["salt-lake-city", "west-jordan"] },
  { slug: "little-rock", name: "Little Rock", stateSlug: "arkansas", stateName: "Arkansas", nearby: ["fayetteville-ar", "fort-smith"] },
  { slug: "akron", name: "Akron", stateSlug: "ohio", stateName: "Ohio", nearby: ["cleveland", "toledo"] },
  { slug: "shreveport", name: "Shreveport", stateSlug: "louisiana", stateName: "Louisiana", nearby: ["baton-rouge", "new-orleans"] },
  { slug: "mobile", name: "Mobile", stateSlug: "alabama", stateName: "Alabama", nearby: ["birmingham", "montgomery"] },
  { slug: "grand-rapids", name: "Grand Rapids", stateSlug: "michigan", stateName: "Michigan", nearby: ["detroit", "ann-arbor"] },
  { slug: "huntsville", name: "Huntsville", stateSlug: "alabama", stateName: "Alabama", nearby: ["birmingham", "mobile"] },
  { slug: "tallahassee", name: "Tallahassee", stateSlug: "florida", stateName: "Florida", nearby: ["jacksonville", "orlando"] },
  { slug: "grand-prairie", name: "Grand Prairie", stateSlug: "texas", stateName: "Texas", nearby: ["dallas", "arlington"] },
  { slug: "hartford", name: "Hartford", stateSlug: "connecticut", stateName: "Connecticut" },
  { slug: "dover", name: "Dover", stateSlug: "delaware", stateName: "Delaware" },
  { slug: "augusta-maine", name: "Augusta", stateSlug: "maine", stateName: "Maine" },
  { slug: "jackson-ms", name: "Jackson", stateSlug: "mississippi", stateName: "Mississippi" },
  { slug: "helena", name: "Helena", stateSlug: "montana", stateName: "Montana" },
  { slug: "concord", name: "Concord", stateSlug: "new-hampshire", stateName: "New Hampshire" },
  { slug: "bismarck", name: "Bismarck", stateSlug: "north-dakota", stateName: "North Dakota" },
  { slug: "providence", name: "Providence", stateSlug: "rhode-island", stateName: "Rhode Island" },
  { slug: "columbia-sc", name: "Columbia", stateSlug: "south-carolina", stateName: "South Carolina" },
  { slug: "pierre", name: "Pierre", stateSlug: "south-dakota", stateName: "South Dakota" },
  { slug: "montpelier", name: "Montpelier", stateSlug: "vermont", stateName: "Vermont" },
  { slug: "charleston-wv", name: "Charleston", stateSlug: "west-virginia", stateName: "West Virginia" },
  { slug: "cheyenne", name: "Cheyenne", stateSlug: "wyoming", stateName: "Wyoming" },

  { slug: "frisco", name: "Frisco", stateSlug: "texas", stateName: "Texas", nearby: ["plano", "dallas"] },
  { slug: "mckinney", name: "McKinney", stateSlug: "texas", stateName: "Texas", nearby: ["frisco", "plano"] },
  { slug: "mesquite", name: "Mesquite", stateSlug: "texas", stateName: "Texas", nearby: ["dallas", "garland"] },
  { slug: "mcallen", name: "McAllen", stateSlug: "texas", stateName: "Texas", nearby: ["brownsville", "laredo"] },
  { slug: "brownsville", name: "Brownsville", stateSlug: "texas", stateName: "Texas", nearby: ["mcallen", "corpus-christi"] },
  { slug: "killeen", name: "Killeen", stateSlug: "texas", stateName: "Texas", nearby: ["austin", "waco"] },
  { slug: "waco", name: "Waco", stateSlug: "texas", stateName: "Texas", nearby: ["austin", "killeen"] },
  { slug: "denton", name: "Denton", stateSlug: "texas", stateName: "Texas", nearby: ["frisco", "plano"] },
  { slug: "oxnard", name: "Oxnard", stateSlug: "california", stateName: "California", nearby: ["los-angeles", "santa-ana"] },
  { slug: "huntington-beach", name: "Huntington Beach", stateSlug: "california", stateName: "California", nearby: ["anaheim", "irvine"] },
  { slug: "ontario", name: "Ontario", stateSlug: "california", stateName: "California", nearby: ["rancho-cucamonga", "san-bernardino"] },
  { slug: "rancho-cucamonga", name: "Rancho Cucamonga", stateSlug: "california", stateName: "California", nearby: ["ontario", "san-bernardino"] },
  { slug: "oceanside", name: "Oceanside", stateSlug: "california", stateName: "California", nearby: ["san-diego", "anaheim"] },
  { slug: "garden-grove", name: "Garden Grove", stateSlug: "california", stateName: "California", nearby: ["anaheim", "santa-ana"] },
  { slug: "elk-grove", name: "Elk Grove", stateSlug: "california", stateName: "California", nearby: ["sacramento", "stockton"] },
  { slug: "santa-rosa", name: "Santa Rosa", stateSlug: "california", stateName: "California", nearby: ["san-francisco", "oakland"] },
  { slug: "glendale-ca", name: "Glendale", stateSlug: "california", stateName: "California", nearby: ["los-angeles", "long-beach"] },
  { slug: "salinas", name: "Salinas", stateSlug: "california", stateName: "California", nearby: ["san-jose", "fresno"] },
  { slug: "fort-lauderdale", name: "Fort Lauderdale", stateSlug: "florida", stateName: "Florida", nearby: ["miami", "hialeah"] },
  { slug: "cape-coral", name: "Cape Coral", stateSlug: "florida", stateName: "Florida", nearby: ["tampa", "orlando"] },
  { slug: "pembroke-pines", name: "Pembroke Pines", stateSlug: "florida", stateName: "Florida", nearby: ["miami", "hialeah"] },
  { slug: "cary", name: "Cary", stateSlug: "north-carolina", stateName: "North Carolina", nearby: ["raleigh", "durham"] },
  { slug: "newport-news", name: "Newport News", stateSlug: "virginia", stateName: "Virginia", nearby: ["norfolk", "virginia-beach"] },
  { slug: "chattanooga", name: "Chattanooga", stateSlug: "tennessee", stateName: "Tennessee", nearby: ["nashville", "atlanta"] },
  { slug: "knoxville", name: "Knoxville", stateSlug: "tennessee", stateName: "Tennessee", nearby: ["nashville", "chattanooga"] },
];


export function getCitiesForState(stateSlug: string) {
  return CITY_LOCATIONS.filter((city) => city.stateSlug === stateSlug);
}

export function getCityByStateAndSlug(stateSlug: string, citySlug: string) {
  return CITY_LOCATIONS.find(
    (city) => city.stateSlug === stateSlug && city.slug === citySlug,
  );
}